package store

import (
	"database/sql"
	"errors"
	"path/filepath"
	"strings"
	"testing"

	"github.com/brunoomariano/luna/src/internal/fsm"
)

// preVersionSchema is the store as it stood before versioning existed.
//
// Written out rather than derived, because the point of these tests is to open a
// file this build did not create. A fixture generated by the current code would
// only ever prove that the current code agrees with itself — which is what the
// test this replaces was doing.
const preVersionSchema = `
CREATE TABLE events (
    task_id  TEXT    NOT NULL,
    seq      INTEGER NOT NULL,
    action   TEXT    NOT NULL,
    payload  TEXT    NOT NULL DEFAULT '',
    blob     TEXT    NOT NULL DEFAULT '',
    at       INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (task_id, seq)
);
CREATE TABLE blobs (
    sha256   TEXT PRIMARY KEY,
    content  BLOB NOT NULL
);
`

// oldStore writes a database in the pre-versioning shape and returns its path.
func oldStore(t *testing.T, blobs ...string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "luna.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("creating an old store: %v", err)
	}
	defer func() { _ = db.Close() }()

	if _, err := db.Exec(preVersionSchema); err != nil {
		t.Fatalf("writing the old schema: %v", err)
	}
	for i, body := range blobs {
		if _, err := db.Exec(
			`INSERT INTO blobs (sha256, content) VALUES (?, ?)`,
			strings.Repeat("a", 63)+string(rune('0'+i)), []byte(body),
		); err != nil {
			t.Fatalf("seeding an old blob: %v", err)
		}
	}
	return path
}

// TestAnOldStoreHoldingArtifactsIsRefusedRatherThanBroken is the failure this
// versioning exists to convert.
//
// `CREATE TABLE IF NOT EXISTS` leaves an older table exactly as it is, so the
// mismatch used to surface at the first insert — mid-stage, as `table blobs has
// no column named task_id`, which names neither the cause nor the fix. Opening is
// where a person can still act.
func TestAnOldStoreHoldingArtifactsIsRefusedRatherThanBroken(t *testing.T) {
	path := oldStore(t, "a contract somebody wrote")

	_, err := OpenAs(path, LunaOwnsTheLog)

	if !errors.Is(err, ErrSchemaTooOld) {
		t.Fatalf("an old store holding artifacts was opened: %v", err)
	}
	// The refusal has to carry what to do about it, or it is the same dead end
	// one step earlier.
	for _, want := range []string{"1 stored artifacts", "sqlite3", "Move the file aside"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal does not say %q: %v", want, err)
		}
	}
}

// TestAnOldStoreThatNeverStoredAnythingIsMigrated is the other branch, and the
// reason the refusal above is not simply "refuse anything old".
//
// A file created and never used has no artifact to lose, so stopping the person
// would be ceremony: every artifact it could strand is zero of them. The log in
// it is not touched either way.
func TestAnOldStoreThatNeverStoredAnythingIsMigrated(t *testing.T) {
	path := oldStore(t)

	s, err := OpenAs(path, LunaOwnsTheLog)
	if err != nil {
		t.Fatalf("an empty old store was refused: %v", err)
	}
	t.Cleanup(func() { _ = s.Close() })

	// And it is a working store afterwards, which is the whole claim: the blob
	// table is the current one, so the insert that used to fail now lands.
	if err := s.AppendAction("OLD-1", fsm.TaskCreated{
		Kind: fsm.KindChore, Flow: fsm.Fingerprint(fsm.DefaultFlow()),
	}); err != nil {
		t.Fatalf("appending to a migrated store: %v", err)
	}
	if err := s.PutBlob(Blob{
		TaskID: "OLD-1", Stage: "setup", Artifact: "setup_report", Seq: 1, Body: []byte("hello"),
	}); err != nil {
		t.Fatalf("storing an artifact in a migrated store: %v", err)
	}
}

// TestAnUnscopedLogIsRefusedAsCentral keeps a former project's identity from
// becoming an empty project key in the global database. The daemon import path
// has the project key and is the only place that can assign it honestly.
func TestAnUnscopedLogIsRefusedAsCentral(t *testing.T) {
	path := oldStore(t)

	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("opening directly: %v", err)
	}
	if _, err := db.Exec(
		`INSERT INTO events (task_id, seq, action, payload) VALUES ('OLD-2', 1, 'TaskCreated', '{"kind":"chore"}')`,
	); err != nil {
		t.Fatalf("seeding the old log: %v", err)
	}
	if err := db.Close(); err != nil {
		t.Fatalf("closing: %v", err)
	}

	_, err = OpenAs(path, LunaOwnsTheLog)
	if !errors.Is(err, ErrSchemaTooOld) || !strings.Contains(err.Error(), "without a project key") {
		t.Fatalf("opening an unscoped log as central = %v", err)
	}
}

// TestAStoreRecordsTheShapeItWasWrittenIn is what the next change will read.
//
// Without the stamp there is no way to tell a database written by an older build
// from a brand new one, and the migration would have to guess from the columns
// every time — which is exactly what it does for version 0 and must not have to
// do again.
func TestAStoreRecordsTheShapeItWasWrittenIn(t *testing.T) {
	path := filepath.Join(t.TempDir(), "luna.db")

	s, err := OpenAs(path, LunaOwnsTheLog)
	if err != nil {
		t.Fatalf("opening: %v", err)
	}
	if err := s.Close(); err != nil {
		t.Fatalf("closing: %v", err)
	}

	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatalf("reopening directly: %v", err)
	}
	defer func() { _ = db.Close() }()

	var version int
	if err := db.QueryRow(`PRAGMA user_version`).Scan(&version); err != nil {
		t.Fatalf("reading the version: %v", err)
	}
	if version != schemaVersion {
		t.Errorf("a fresh store records version %d, want %d", version, schemaVersion)
	}
}

func TestSchemaHelpersReportAClosedDatabase(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}

	checks := []struct {
		name string
		run  func() error
	}{
		{name: "migrate", run: func() error { return migrate(db) }},
		{name: "require current", run: func() error { return requireCurrentSchema(db) }},
		{name: "table exists", run: func() error { _, err := tableExists(db, "events"); return err }},
		{name: "column exists", run: func() error { _, err := tableHasColumn(db, "events", "project"); return err }},
		{name: "version zero", run: func() error { return migrateToOne(db) }},
		{name: "pre-version blobs", run: func() error { _, err := isPreVersionBlobs(db); return err }},
		{name: "rebuild", run: func() error { return rebuildWithProject(db, "events") }},
		{name: "unscoped rows", run: func() error { return refuseUnscopedRows(db, "events") }},
	}
	for _, check := range checks {
		if err := check.run(); err == nil {
			t.Errorf("%s ignored a closed database", check.name)
		}
	}
}

func TestMigrationRejectsAnUnknownTable(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if err := rebuildWithProject(db, "unknown"); err == nil {
		t.Fatal("an unknown table was given an invented migration")
	}
}

func TestMigrationAcceptsAlreadyScopedAndMissingTables(t *testing.T) {
	path := filepath.Join(t.TempDir(), "partially-migrated.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`
		PRAGMA user_version = 1;
		CREATE TABLE events (
			project TEXT NOT NULL, task_id TEXT NOT NULL, seq INTEGER NOT NULL,
			action TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '', at INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (project, task_id, seq));
	`); err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}

	s, err := OpenAs(path, LunaOwnsTheLog)
	if err != nil {
		t.Fatalf("opening a partially migrated store: %v", err)
	}
	t.Cleanup(func() { _ = s.Close() })
}

func TestMigrationReportsMalformedVersionOneTables(t *testing.T) {
	path := filepath.Join(t.TempDir(), "malformed.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`
		PRAGMA user_version = 1;
		CREATE TABLE events (task_id TEXT PRIMARY KEY);
	`); err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}
	if _, err := OpenAs(path, LunaOwnsTheLog); err == nil {
		t.Fatal("a malformed version-one event table was migrated")
	}
	db, err = sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = db.Close() }()
	hasProject, err := tableHasColumn(db, "events", "project")
	if err != nil {
		t.Fatal(err)
	}
	if hasProject {
		t.Fatal("a failed migration left a replacement events table behind")
	}
	leftover, err := tableExists(db, "events_v1")
	if err != nil {
		t.Fatal(err)
	}
	if leftover {
		t.Fatal("a failed migration left its renamed source table behind")
	}
}

func TestMigrationReportsAnOldBlobView(t *testing.T) {
	path := filepath.Join(t.TempDir(), "view.db")
	db, err := sql.Open("sqlite", path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := db.Exec(`CREATE VIEW blobs AS SELECT '' AS sha256, '' AS content WHERE 0`); err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}
	if _, err := OpenAs(path, LunaOwnsTheLog); err == nil {
		t.Fatal("an old blob view was silently replaced")
	}
}

func TestMigrateToTwoReportsAClosedDatabase(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	if err := db.Close(); err != nil {
		t.Fatal(err)
	}
	if err := migrateToTwo(db); err == nil {
		t.Fatal("the version-two migration ignored a closed database")
	}
}
